#!/bin/bash

if [ "$2" == "" ]
then
	echo Usage: $0 new-app-short-name new-app-long-name
	echo e.g. $0 mysynth \"My Synthesizer\"
else
	rpl -R canofbeats $1 .
	rpl -R "CanOfBeats" $2 .
	bzr mv src/cx/mccormick/canofbeats src/cx/mccormick/$1
fi
